# Read the Docs configuration file for Sphinx projects

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: true
  nitpicky: true
  fail_on_build_failure: true
